require("../examples/simple")

require("./client")
require("./find")
require("./update")
require("./findOne")
require("./remove")
require("./mapReduce")
require("./findAndModify")
require("./findAndRemove")
